package com.skillstorm.music.models;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/*
 * this class is an entity -- it maps to a table in our database -- one record in that table = one object of this class
 */

// this annotation states that this class is a DB entity
@Entity
// this annotation states which table this class corresponds to
// if your class name DOES NOT match the table name, you can use @Table(name = "actual_table_name")
// if you don't specify the name, it assumes the class name is the table name
@Table
public class Label {
	
	// this specifies that this property is the primary key for this table
	@Id
	// this specifies that this column's values are generated by the persistence provider (database)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	// this specifies which column this variable goes with
	// same rules apply for naming -- if it doesn't match, you can say @Column(name = "actual_column_name")
	@Column
	private int id;
	
	// JPA auto-converts column/table names like label_name to their Java equivalents, like labelName
	@Column
	private String labelName;
	
	// on the non-controlling side, we only need to state the property on the controlling side that maps the relationship
	@OneToOne(mappedBy = "label")
	@JsonIgnoreProperties({"label"})
	private LabelHistory labelHistory;
	
	@OneToMany(mappedBy = "label")
	@JsonIgnoreProperties({"label"})
	private List<Artist> artists;
	
	public Label() {
		super();
	}

	public Label(int id, String labelName, LabelHistory labelHistory, List<Artist> artists) {
		super();
		this.id = id;
		this.labelName = labelName;
		this.labelHistory = labelHistory;
		this.artists = artists;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLabelName() {
		return labelName;
	}

	public void setLabelName(String labelName) {
		this.labelName = labelName;
	}

	public LabelHistory getLabelHistory() {
		return labelHistory;
	}

	public void setLabelHistory(LabelHistory labelHistory) {
		this.labelHistory = labelHistory;
	}

	public List<Artist> getArtists() {
		return artists;
	}

	public void setArtists(List<Artist> artists) {
		this.artists = artists;
	}
	
}
