package com.skillstorm.music.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/*
 * this class is an entity -- it maps to a table in our database -- one record in that table = one object of this class
 */

// this annotation states that this class is a DB entity
@Entity
// this annotation states which table this class corresponds to
// if your class name DOES NOT match the table name, you can use @Table(name = "actual_table_name")
// if you don't specify the name, it assumes the class name is the table name
@Table
public class Label {
	
	// this specifies that this property is the primary key for this table
	@Id
	// this specifies that this column's values are generated by the persistence provider (database)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	// this specifies which column this variable goes with
	// same rules apply for naming -- if it doesn't match, you can say @Column(name = "actual_column_name")
	@Column
	private int id;
	
	// JPA auto-converts column/table names like label_name to their Java equivalents, like labelName
	@Column
	private String labelName;
	
	public Label() {
		super();
	}

	public Label(int id, String labelName) {
		super();
		this.id = id;
		this.labelName = labelName;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLabelName() {
		return labelName;
	}

	public void setLabelName(String labelName) {
		this.labelName = labelName;
	}
	
}
